"use client";
import {useEffect,useMemo,useState} from "react";
import {foundationDifficulties,foundationLessons,foundationProjects} from "./lib/foundation-curriculum.mjs";
import {evaluateFoundationLesson,fieldMinimum} from "./lib/foundation-evaluation.mjs";
import {emptyFoundation,loadFoundation,saveFoundation} from "./lib/foundation-storage.mjs";

const initialLesson=()=>({status:"not_started",answers:{},initialAnswers:{},score:0,bestScore:0,attempts:0,defenseAnswer:"",miniCaseAnswer:null,provocationAnswer:null,comparisonReasons:[],reviewAnswer:null,feedback:null,history:[],completedAt:null});
const criterionNames={specificity:"Конкретность",coherence:"Логическая связность",customer:"Задача клиента",verifiability:"Проверяемость",alternative:"Отличие от альтернатив",argumentation:"Аргументация"};
const projectStarters={
  cheget:{product:"Интернет-магазин одежды CheGET.store",customer:"Покупатель, которому нужен готовый образ для конкретного события",situation:"До события осталось несколько дней, а подходящего комплекта нет",job:"Быстро собрать совместимый образ без долгого поиска по разным магазинам",outcome:"Получить уверенный готовый образ к нужной дате",proof:"Комплект собран за 20 минут, доставлен до события, доля возвратов измеряется"},
  coffee:{product:"Кофейня «Север»",customer:"Сотрудник офиса рядом с кофейней, который идёт на работу",situation:"Утром до начала рабочего дня осталось 10–15 минут",job:"Взять привычный завтрак без очереди и опоздания",outcome:"Получить напиток и перекус за 7 минут",proof:"90% утренних заказов выданы не дольше чем за 7 минут"},
  saas:{product:"SaaS-сервис «Пульс»",customer:"Новый руководитель команды до 10 человек",situation:"Команда начинает первый совместный проект без общего процесса",job:"За день распределить работу и сделать ответственность видимой",outcome:"Запустить первую общую задачу с владельцем и сроком",proof:"Не менее 30% новых команд создают общую задачу в первые 24 часа"},
};

function inheritedAnswers(index,foundation){
  const get=i=>foundation.lessons?.[foundationLessons[i].id]?.answers||{};
  if(index===1){const one=get(0);return {group:[one.customer,one.job].filter(Boolean).join(", "),demandSituation:one.situation||"",marketEvidence:one.proof||""};}
  if(index===2){const two=get(1);return {segment1:[two.group,two.demandSituation,two.alternatives].filter(Boolean).join(" · ")};}
  if(index===3){const one=get(0),two=get(1),three=get(2);return {valueSegment:three.priority||"",valueSituation:one.situation||two.demandSituation||"",valueOutcome:one.outcome||"",valueAlternative:two.alternatives||""};}
  if(index===4){const four=get(3);return {positionSegment:four.valueSegment||"",positionAlternative:four.valueAlternative||"",positionDifference:four.difference||"",positionProof:four.valueProof||""};}
  return {};
}

export default function FoundationTrainer({lessonIndex,mode,onMode,onCompleted,onNext,onProgressReset}){
  const[foundation,setFoundation]=useState(emptyFoundation()),[loaded,setLoaded]=useState(false),[saveState,setSaveState]=useState("Загрузка…"),[notice,setNotice]=useState(""),[checked,setChecked]=useState(false),[showFormula,setShowFormula]=useState(false);
  const lesson=foundationLessons[lessonIndex],lessonState={...initialLesson(),...(foundation.lessons?.[lesson.id]||{})},difficulty=foundation.difficulty||mode||"beginner";
  useEffect(()=>{const result=loadFoundation(localStorage);setFoundation(result.state);setLoaded(true);setSaveState(result.error?"Ошибка сохранения":"Данные сохранены");setNotice(result.migrated?"Мы сохранили ваш ответ из прежней версии. Он не потерян — разложите его по новым полям и пройдите честную проверку.":result.restored?"Данные восстановлены из браузера.":"");onMode?.(result.state.difficulty);},[]);
  useEffect(()=>{setChecked(false);setShowFormula(false);},[lessonIndex]);
  const report=useMemo(()=>evaluateFoundationLesson(lessonIndex,lessonState,foundation),[lessonIndex,lessonState,foundation]),project=foundation.selectedProject;
  const persist=next=>{const result=saveFoundation(localStorage,next);setFoundation(result.state);setSaveState(result.ok?"Данные сохранены":"Ошибка сохранения");return result.ok;};
  const patchLesson=(patch,markEditing=true)=>{const current={...initialLesson(),...(foundation.lessons?.[lesson.id]||{})},nextLesson={...current,...patch};if(markEditing&&current.status==="completed")nextLesson.status="in_progress";const next={...foundation,lessons:{...foundation.lessons,[lesson.id]:nextLesson}};persist(next);setChecked(false);};
  const chooseDifficulty=value=>{onMode?.(value);persist({...foundation,difficulty:value});};
  const chooseProject=entry=>{const changed=foundation.selectedProject&&foundation.selectedProject.id!==entry.id;if(!changed){persist({...foundation,selectedProject:{id:entry.id,name:entry.name}});return;}const lessons=Object.fromEntries(Object.entries(foundation.lessons||{}).map(([id,state])=>[id,{...state,status:state.status==="completed"?"needs_revision":state.status,projectId:null,completedAt:null}]));persist({...foundation,selectedProject:{id:entry.id,name:entry.name},lessons});onProgressReset?.();setNotice("Проект изменён. Прежние ответы сохранены, но завершённые уроки нужно перепроверить в новом контексте.");};
  const changeProjectName=value=>persist({...foundation,selectedProject:{id:"own",name:value}});
  const changeAnswer=(key,value)=>patchLesson({answers:{...lessonState.answers,[key]:value},status:"practice_started"});
  const toggleReason=index=>{const current=lessonState.comparisonReasons||[],next=current.includes(index)?current.filter(value=>value!==index):[...current,index];patchLesson({comparisonReasons:next},false);};
  const prefill=()=>{const starter=lessonIndex===0?projectStarters[project?.id]||{}:inheritedAnswers(lessonIndex,foundation);patchLesson({answers:{...lessonState.answers,...starter},status:"practice_started"});};
  const checkAnswer=()=>{const evaluation=evaluateFoundationLesson(lessonIndex,lessonState,foundation),attempt=Number(lessonState.attempts||0)+1,nextLesson={...lessonState,projectId:project.id,status:evaluation.score>=evaluation.threshold&&evaluation.requiredComplete?"checked":"needs_revision",initialAnswers:lessonState.attempts?lessonState.initialAnswers:{...lessonState.answers},score:evaluation.score,bestScore:Math.max(Number(lessonState.bestScore||0),evaluation.score),attempts:attempt,feedback:evaluation,history:[...(lessonState.history||[]),{attempt,score:evaluation.score,issues:evaluation.issues.slice(0,3),at:new Date().toISOString()}].slice(-5)};persist({...foundation,lessons:{...foundation.lessons,[lesson.id]:nextLesson}});setChecked(true);};
  const finish=()=>{const current={...lessonState},evaluation=evaluateFoundationLesson(lessonIndex,current,foundation);if(!evaluation.readyToComplete){setChecked(true);return;}const nextLesson={...current,status:"completed",score:evaluation.score,bestScore:Math.max(current.bestScore||0,evaluation.score),feedback:evaluation,completedAt:new Date().toISOString()},next={...foundation,lessons:{...foundation.lessons,[lesson.id]:nextLesson}};if(persist(next)){onCompleted?.(lessonIndex,`${lesson.title}: ${evaluation.score}/100 · ${Object.values(current.answers).filter(Boolean).join(" | ")}`);onNext?.();}};
  const blocker=!project?"Выберите проект, с которым будете работать во всех пяти уроках.":lessonState.provocationAnswer===null?"Сначала ответьте на провокационный вопрос.":lessonState.miniCaseAnswer===null?"Сначала решите мини-кейс.":(lessonState.comparisonReasons||[]).length<2?"Отметьте минимум две причины, почему сильный ответ лучше.":!Object.values(lessonState.answers||{}).some(value=>String(value).trim())?"Заполните практическое задание.":"";
  const completionBlocker=report.score<report.threshold?`Нужно набрать минимум ${report.threshold} баллов. Сейчас ${report.score}.`:!report.requiredComplete?"Исправьте обязательные замечания в практической работе.":String(lessonState.defenseAnswer||"").trim().length<(foundationDifficulties[difficulty]?.defenseMin||65)?`Защитите решение: минимум ${foundationDifficulties[difficulty]?.defenseMin||65} символов.`:lessonState.reviewAnswer===null?"Ответьте на вопрос закрепления.":"";
  if(!loaded)return <div className="foundation-loading">Восстанавливаем учебный проект…</div>;
  return <div className="foundation-lesson">
    <div className="lesson-meta"><span>УРОК {lessonIndex+1} ИЗ 5</span><span>{lesson.time}</span></div>
    <div className="foundation-title"><div><small>НАВЫК УРОКА</small><b>{lesson.skill}</b></div><span>{saveState}</span></div>
    <h1>{lesson.title}</h1>
    {notice&&<div className="restore-notice">{notice}<button onClick={()=>setNotice("")} aria-label="Скрыть уведомление">×</button></div>}
    <section className="lesson-stage provocation"><span>01</span><div><small>ПРОВОКАЦИЯ · ОТВЕТЬТЕ ДО ТЕОРИИ</small><h2>{lesson.provocation.question}</h2><div className="foundation-options">{lesson.provocation.options.map((option,index)=><button className={lessonState.provocationAnswer===index?"selected":""} onClick={()=>patchLesson({provocationAnswer:index,status:"theory"},false)} key={option}>{String.fromCharCode(65+index)}. {option}</button>)}</div>{lessonState.provocationAnswer!==null&&<p>Ответ сохранён. Вернёмся к нему после разбора.</p>}</div></section>
    {lessonState.provocationAnswer!==null&&<>
      <section className="lesson-stage"><span>02</span><div><small>СУТЬ УРОКА</small><p className="lesson-essence">{lesson.essence}</p><div className="provocation-return"><b>Возвращаемся к первому вопросу</b><p>Ваш выбор: {lesson.provocation.options[lessonState.provocationAnswer]}. Рабочий вывод: {lesson.provocation.options[lesson.provocation.best]}.</p></div><button className="text-button" onClick={()=>setShowFormula(!showFormula)}>{showFormula?"Скрыть формулу":"Открыть формулу мышления"} →</button>{showFormula&&<div className="lesson-formula">{lesson.formula}</div>}</div></section>
      <section className="lesson-stage"><span>03</span><div><small>НЕ ПУТАЙ</small><div className="contrast-table"><b>Это ещё не рабочее определение</b><b>Это уже можно проверить</b>{lesson.contrast.flatMap((pair,index)=>[<p key={`weak-${index}`}>{pair[0]}</p>,<p key={`strong-${index}`}>{pair[1]}</p>])}</div></div></section>
      <section className="lesson-stage"><span>04</span><div><small>СЛАБЫЙ И СИЛЬНЫЙ ОТВЕТ</small><h3>{lesson.example.task}</h3><div className="answer-compare"><article><b>Слабый</b><p>{lesson.example.weak}</p></article><article><b>Сильный</b><p>{lesson.example.strong}</p></article></div><h3>Почему второй ответ сильнее? Выберите минимум два пункта.</h3><div className="reason-grid">{lesson.example.reasons.map((reason,index)=><button className={(lessonState.comparisonReasons||[]).includes(index)?"selected":""} onClick={()=>toggleReason(index)} key={reason}>{(lessonState.comparisonReasons||[]).includes(index)?"✓":"○"} {reason}</button>)}</div></div></section>
      <section className="lesson-stage"><span>05</span><div><small>МИНИ-КЕЙС</small><h2>{lesson.miniCase.question}</h2><div className="foundation-options">{lesson.miniCase.options.map((option,index)=><button className={lessonState.miniCaseAnswer===index?(index===lesson.miniCase.best?"selected correct":"selected wrong"):""} onClick={()=>patchLesson({miniCaseAnswer:index,status:"case_done"},false)} key={option}>{String.fromCharCode(65+index)}. {option}</button>)}</div>{lessonState.miniCaseAnswer!==null&&<div className={lessonState.miniCaseAnswer===lesson.miniCase.best?"case-explanation good":"case-explanation"}><b>{lessonState.miniCaseAnswer===lesson.miniCase.best?"Сильная логика":"Разберите риск ответа"}</b><p>{lesson.miniCase.feedback[lessonState.miniCaseAnswer]}</p></div>}</div></section>
    </>}
    {lessonState.miniCaseAnswer!==null&&<>
      <section className="lesson-stage"><span>06</span><div><small>ЕДИНЫЙ ПРОЕКТ НА ПЯТЬ УРОКОВ</small><div className="project-grid">{foundationProjects.map(entry=><button className={project?.id===entry.id?"selected":""} onClick={()=>chooseProject(entry)} key={entry.id}><b>{entry.name}</b><small>{entry.description}</small></button>)}</div>{project?.id==="own"&&<label className="field-label"><span>Название вашего проекта</span><input value={project.name==="Свой бизнес"?"":project.name} onChange={event=>changeProjectName(event.target.value)} placeholder="Введите название"/></label>}</div></section>
      {project&&<section className="lesson-stage practice-stage"><span>07</span><div><small>РАБОТА С ПРОЕКТОМ · {project.name}</small><div className="difficulty-row">{Object.entries(foundationDifficulties).map(([key,value])=><button className={difficulty===key?"selected":""} onClick={()=>chooseDifficulty(key)} key={key}><b>{value.name}</b><small>Порог {value.threshold}/100</small></button>)}</div><p className="difficulty-note">{foundationDifficulties[difficulty].note}</p>{(difficulty==="beginner"||lessonIndex>0)&&<button className="text-button" onClick={prefill}>{lessonIndex?"Подставить основу предыдущих уроков":"Подставить учебный старт"} →</button>}{lessonState.answers?.legacyAnswer&&<div className="legacy-answer"><b>Ваш старый ответ</b><p>{lessonState.answers.legacyAnswer}</p></div>}<div className="foundation-fields">{lesson.fields.map((field,index)=><label className={`field-label${report.missing.includes(field.key)&&checked?" needs-work":""}`} key={field.key}><span>{index+1}. {field.label}</span><textarea value={lessonState.answers?.[field.key]||""} onChange={event=>changeAnswer(field.key,event.target.value)} placeholder={difficulty==="pro"?"Сформулируйте без подсказки…":field.placeholder}/>{difficulty==="beginner"&&<small>{field.hint||`Минимум ${fieldMinimum(field,difficulty)} символов.`}</small>}</label>)}</div>{difficulty==="pro"&&<label className="field-label pro-challenge"><span>Вопрос совета директоров: какой риск или контраргумент разрушит решение?</span><textarea value={lessonState.proChallenge||""} onChange={event=>patchLesson({proChallenge:event.target.value,status:"practice_started"})} placeholder="Риск, контраргумент и защитная метрика…"/></label>}<div className="check-actions"><button className="primary" disabled={Boolean(blocker)} onClick={checkAnswer}>Проверить ответ →</button><span>{blocker||"Система покажет конкретные сильные стороны и слабые места."}</span></div>
        {(checked||lessonState.feedback)&&<div className="evaluation"><div className="evaluation-head"><strong>{report.score}/100</strong><div><small>ПОРОГ {report.threshold}</small><h2>{report.status}</h2><p>Попыток: {lessonState.attempts||0} · лучший результат: {Math.max(report.score,lessonState.bestScore||0)}</p></div></div><div className="criteria-grid">{Object.entries(report.criteria).map(([key,value])=><div key={key}><span>{criterionNames[key]}</span><b>{value}</b><i><em style={{width:`${Math.min(100,value/(key==="verifiability"||key==="alternative"?15:key==="argumentation"?10:20)*100)}%`}}/></i></div>)}</div><div className="feedback-grid"><article className="positive"><b>Что получилось</b><ul>{report.strengths.map(item=><li key={item}>{item}</li>)}</ul></article><article><b>Что ослабляет ответ</b><ul>{report.issues.map(item=><li key={item}>{item}</li>)}</ul></article><article><b>Что исправить сейчас</b><ol>{report.actions.map(item=><li key={item}>{item}</li>)}</ol><button className="text-button" onClick={()=>setChecked(false)}>Исправить ответ →</button></article></div></div>}
        {lessonState.attempts>0&&<section className="defense"><small>08 · ЗАЩИТА РЕШЕНИЯ</small><h2>{lesson.defense}</h2><textarea value={lessonState.defenseAnswer||""} onChange={event=>patchLesson({defenseAnswer:event.target.value},false)} placeholder="Защитите решение фактами, ограничениями и логикой…"/><span>{String(lessonState.defenseAnswer||"").trim().length}/{foundationDifficulties[difficulty].defenseMin} символов</span>{lessonState.initialAnswers&&Object.keys(lessonState.initialAnswers).length>0&&lessonState.attempts>1&&<details><summary>Сравнить с первой попыткой</summary><dl>{lesson.fields.filter(field=>lessonState.initialAnswers[field.key]).map(field=><div key={field.key}><dt>{field.label}</dt><dd>{lessonState.initialAnswers[field.key]}</dd></div>)}</dl></details>}</section>}
        {String(lessonState.defenseAnswer||"").trim().length>=foundationDifficulties[difficulty].defenseMin&&<section className="review-question"><small>09 · ЗАКРЕПЛЕНИЕ</small><h2>{lesson.review.question}</h2><div className="foundation-options">{lesson.review.options.map((option,index)=><button className={lessonState.reviewAnswer===index?"selected":""} onClick={()=>patchLesson({reviewAnswer:index},false)} key={option}>{option}</button>)}</div>{lessonState.reviewAnswer!==null&&<p>{lessonState.reviewAnswer===lesson.review.best?"Ответ связывает уроки в единую систему.":"Вернитесь к ключевой мысли предыдущего урока и попробуйте ещё раз."}</p>}</section>}
        <section className="lesson-result"><small>ОДНА МЫСЛЬ, КОТОРУЮ НУЖНО ЗАПОМНИТЬ</small><blockquote>{lesson.memory}</blockquote><div className="lesson-outcomes"><p><b>Поняли:</b> чем рабочее маркетинговое решение отличается от общего описания.</p><p><b>Создали:</b> часть документа «Маркетинговый фундамент проекта».</p><p><b>Навык:</b> {lesson.skill}.</p><p><b>Дальше:</b> {lessonIndex<4?`урок «${foundationLessons[lessonIndex+1].title}» использует этот результат.`:"соберите итоговый документ и переходите к исследованиям."}</p><p><b>Результат:</b> {report.score}/100 · лучший {Math.max(report.score,lessonState.bestScore||0)}/100.</p></div><button className="primary" disabled={!report.readyToComplete} onClick={finish}>{lessonState.status==="completed"?"Обновить результат":"Завершить урок"} →</button>{!report.readyToComplete&&<p>{completionBlocker||"Пройдите все обязательные этапы урока."}</p>}</section>
      </div></section>}
    </>}
  </div>;
}
