"use client";
import {useEffect,useMemo,useState} from "react";
import {buildBusinessMethodPlans,businessProfileReady} from "../lib/business-diagnostic.mjs";
import {marketingMethods,methodCategories} from "../library/methods.mjs";

const empty={name:"",industry:"",product:"",customer:"",problem:"",goal:"",alternatives:"",geography:"",market:"Россия",price:"",channels:"",evidence:"",constraints:""};
const fields=[
  ["name","Название бизнеса","Например: Север"],["industry","Отрасль","Образование, SaaS, производство, ритейл…"],["product","Что вы продаёте?","Конкретный продукт, услуга или подписка"],["customer","Кто принимает решение о покупке?","Не «все», а роль, ситуация и поведение"],["problem","Главная наблюдаемая проблема","Например: много первых покупок, мало повторных"],["goal","Какой результат нужен бизнесу?","Измеримое изменение и горизонт"],["alternatives","Как клиент решает задачу сейчас?","Конкурент, ручной процесс, отказ от решения"],["geography","Где работает бизнес?","Город, регион, страна или несколько рынков"],["price","Цена и модель дохода","Средний чек, подписка, комиссия…"],["channels","Текущие каналы привлечения и продаж","Поиск, партнёры, отдел продаж, CRM…"],["evidence","Какие данные уже есть?","Продажи, интервью, воронка, когорты…"],["constraints","Ограничения и риски","Бюджет, команда, сезонность, регулирование…"],
];
const demo={name:"Онлайн-школа «Практика»",industry:"Дополнительное образование",product:"подписка на практические тренажёры маркетинга",customer:"начинающие маркетологи и руководители небольших команд",problem:"многие регистрируются, но не выполняют первое задание",goal:"повысить активацию и удержание на 30-й день",alternatives:"бесплатные статьи, видео и традиционные курсы",geography:"Россия и русскоязычные рынки",market:"Россия",price:"2 900 ₽ в месяц",channels:"поиск, партнёрства с вузами, контент и CRM",evidence:"воронка регистрации и несколько интервью с учениками",constraints:"небольшая команда, ограниченный рекламный бюджет и защита данных учеников"};
const categoryByTitle=Object.fromEntries(marketingMethods.map(method=>[method.title,method.category]));

export default function BusinessDiagnostic(){
  const[profile,setProfile]=useState(empty),[generated,setGenerated]=useState(false),[category,setCategory]=useState("Все"),[open,setOpen]=useState(null),[loaded,setLoaded]=useState(false);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("olymp-business-diagnostic")||"null");if(saved)setProfile({...empty,...saved})}catch{}setLoaded(true)},[]);
  const update=(key,value)=>{const next={...profile,[key]:value};setProfile(next);setGenerated(false);localStorage.setItem("olymp-business-diagnostic",JSON.stringify(next))};
  const plans=useMemo(()=>buildBusinessMethodPlans(profile),[profile]);
  const visible=plans.filter(plan=>category==="Все"||categoryByTitle[plan.title]===category);
  const ready=businessProfileReady(profile);
  const fillDemo=()=>{setProfile(demo);setGenerated(false);localStorage.setItem("olymp-business-diagnostic",JSON.stringify(demo))};
  const download=()=>{const lines=["МАРКЕТИНГ ОЛИМП — РАСПАКОВКА БИЗНЕСА",`Бизнес: ${profile.name}`,`Продукт: ${profile.product}`,`Клиент: ${profile.customer}`,`Проблема: ${profile.problem}`,`Цель: ${profile.goal}`,"",...plans.flatMap(plan=>[plan.title,plan.context,`Вопрос: ${plan.question}`,`Черновик: ${plan.draft}`,`Первый шаг: ${plan.action}`,`Метрика: ${plan.metric}`,""]),"Граница: это автоматически собранный стратегический черновик, а не доказанный вывод или юридическая рекомендация."],blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="business-marketing-diagnostic.txt";a.click();URL.revokeObjectURL(url)};
  return <main id="main-content" className="business-diagnostic-page"><header><a href="../library/">← В библиотеку методов</a><small>ПРОТОТИП РАСШИРЕННОГО ПРОДУКТА · ДАННЫЕ ТОЛЬКО В БРАУЗЕРЕ</small><h1>Распакуйте бизнес для стратегии</h1><p>Опишите контекст один раз. Тренажёр превратит его в 28 рабочих черновиков: исследования, стратегию, привлечение и аналитику.</p><div className="paid-concept"><b>Сейчас: бесплатный локальный прототип</b><span>В будущей платной версии могут появиться AI-разбор, история версий, командная работа и проверка экспертом. Оплата пока не подключена.</span><a href="../pro/">Оставить заявку на ранний доступ к Pro →</a></div></header>
    <section className="business-form"><div className="form-heading"><div><small>ШАГ 1</small><h2>Контекст бизнеса</h2><p>Обязательные поля отмечены звёздочкой. Не вводите персональные данные или коммерческую тайну.</p></div><button type="button" onClick={fillDemo}>Заполнить учебный пример</button></div><div className="business-fields">{fields.map(([key,label,placeholder])=><label key={key}><b>{label}{["name","product","customer","problem","goal"].includes(key)&&" *"}</b>{["problem","goal","evidence","constraints"].includes(key)?<textarea value={profile[key]} onChange={event=>update(key,event.target.value)} placeholder={placeholder}/>:<input value={profile[key]} onChange={event=>update(key,event.target.value)} placeholder={placeholder}/>}</label>)}<fieldset><legend>Основной рынок методических примеров</legend><div>{["Россия","США","Оба рынка"].map(item=><button type="button" className={profile.market===item?"active":""} onClick={()=>update("market",item)} key={item}>{item}</button>)}</div></fieldset></div><div className="generate-panel"><button className="primary" disabled={!ready} onClick={()=>{setGenerated(true);setOpen(null)}}>Разобрать по 28 инструментам →</button><span>{ready?"Профиль готов к первому разбору":"Заполните название, продукт, клиента, проблему и цель"}</span></div></section>
    {generated&&<><section className="strategy-core"><small>АВТОМАТИЧЕСКИЙ ЧЕРНОВИК · ТРЕБУЕТ ПРОВЕРКИ</small><h2>{profile.name}</h2><div><article><b>Продукт</b><p>{profile.product}</p></article><article><b>Клиент</b><p>{profile.customer}</p></article><article><b>Проблема</b><p>{profile.problem}</p></article><article><b>Цель</b><p>{profile.goal}</p></article></div><p>Это структурирование введённого текста, а не подтверждение рыночного спроса. Каждый вывод ниже сформулирован как вопрос, черновик и следующий шаг для сбора доказательств.</p></section><section className="business-results"><div className="results-head"><div><small>ШАГ 2</small><h2>28 инструментов для вашего бизнеса</h2></div><button onClick={download}>Скачать стратегический черновик ↓</button></div><div className="result-filters">{methodCategories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><div className="business-methods">{visible.map((plan,index)=>{const active=open===plan.title;return <article key={plan.title}><button className="business-method-title" aria-expanded={active} onClick={()=>setOpen(active?null:plan.title)}><span>{String(index+1).padStart(2,"0")}</span><div><small>{categoryByTitle[plan.title]}</small><h3>{plan.title}</h3></div><b>{active?"−":"+"}</b></button>{active&&<div className="business-method-body"><p className="method-context">{plan.context}</p><dl><div><dt>Главный вопрос</dt><dd>{plan.question}</dd></div><div><dt>Черновик для вашего бизнеса</dt><dd>{plan.draft}</dd></div><div><dt>Первый рабочий шаг</dt><dd>{plan.action}</dd></div><div><dt>Как измерить</dt><dd>{plan.metric}</dd></div></dl><a href="../library/">Открыть полную инструкцию метода →</a></div>}</article>})}</div></section><section className="diagnostic-boundary"><h2>Что нельзя автоматизировать этой формой</h2><p>Она не проверяет достоверность ваших данных, размер рынка, причинность, применимое законодательство и реалистичность финансовых допущений. Перед инвестициями, запуском рекламы или обработкой персональных данных нужен человеческий аудит и первичные источники для выбранной страны.</p><div><a href="../sources/">Источники РФ и США →</a><a href="../cases/">Потренироваться на кейсе →</a></div></section></>}
    {loaded&&!generated&&<section className="diagnostic-preview"><b>Что появится после заполнения</b><span>28 персонализированных карточек</span><span>Стратегическое ядро</span><span>Первые действия и метрики</span><span>Текстовый экспорт</span></section>}
  </main>}

