"use client";
import {useEffect,useState} from "react";

const steps=[
 {title:"Проблема и решение",intro:"Исследование начинается с решения, которое предстоит принять, а не с желания «узнать аудиторию».",fields:[["decision","Какое решение нужно принять?","Например: выбрать сегмент для запуска нового тарифа"],["problem","Что сейчас неизвестно?","Каких данных не хватает для решения"]]},
 {title:"Аудитория",intro:"Выберите людей с конкретным опытом и поведением — они смогут рассказать о реальной ситуации.",fields:[["audience","Кого нужно исследовать?","Поведение, ситуация, период времени"],["exclude","Кого не нужно включать?","Границы выборки помогают не смешивать разные задачи"]]},
 {title:"Гипотезы",intro:"До интервью зафиксируйте предположения. Так исследование проверит мышление, а не подтвердит удобную историю.",fields:[["hypotheses","Какие 3 гипотезы проверяем?","1. …\n2. …\n3. …"],["signals","Какие сигналы подтвердят или опровергнут их?","Наблюдаемое поведение, факты, частота"]]},
 {title:"Вопросы и результат",intro:"Спрашивайте о прошлом поведении и конкретных ситуациях, а не о намерениях и фантазиях.",fields:[["questions","Запишите 5 вопросов интервью","Расскажите о последнем случае, когда…"],["output","Как будет выглядеть результат?","Таблица инсайтов, карта пути, рекомендации"]]}
];

export default function ResearchModule(){const[step,setStep]=useState(0),[data,setData]=useState({});useEffect(()=>{try{setData(JSON.parse(localStorage.getItem("olymp-research")||"{}"))}catch{}},[]);const update=(k,v)=>{const next={...data,[k]:v};setData(next);localStorage.setItem("olymp-research",JSON.stringify(next))};const keys=steps.flatMap(x=>x.fields.map(y=>y[0])),filled=keys.filter(k=>(data[k]||"").trim().length>15).length,progress=Math.round(filled/keys.length*100);const checks=[{x:"Есть конкретное бизнес-решение",ok:(data.decision||"").length>20},{x:"Аудитория описана через поведение",ok:(data.audience||"").length>25},{x:"Записано не менее трёх гипотез",ok:(data.hypotheses||"").split("\n").filter(Boolean).length>=3},{x:"Вопросы обращены к прошлому опыту",ok:/последн|расскаж|вспомн|случа|делал/.test((data.questions||"").toLowerCase())},{x:"Определён формат результата",ok:(data.output||"").length>15}];const download=()=>{const text=["МАРКЕТИНГ ОЛИМП — ИССЛЕДОВАТЕЛЬСКИЙ БРИФ","",...steps.flatMap(s=>[s.title,...s.fields.flatMap(([k,label])=>[label,data[k]||"—",""])])].join("\n"),blob=new Blob([text],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="research-brief.txt";a.click();URL.revokeObjectURL(url)};return <main id="main-content" className="research-page"><header><a href="../">← На главную</a><small>МОДУЛЬ 02</small><h1>Маркетинговые исследования</h1><p>Соберите исследование, которое помогает принять решение, а не просто производит красивый отчёт.</p><div className="research-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div></header><div className="research-layout"><aside>{steps.map((x,i)=><button className={step===i?"active":""} onClick={()=>setStep(i)} key={x.title}><span>{i+1}</span>{x.title}</button>)}</aside><section className="research-work"><small>ШАГ {step+1} ИЗ {steps.length}</small><h2>{steps[step].title}</h2><p className="research-intro">{steps[step].intro}</p>{steps[step].fields.map(([key,label,placeholder])=><label key={key}><b>{label}</b><textarea value={data[key]||""} onChange={e=>update(key,e.target.value)} placeholder={placeholder}/><span>Сохраняется автоматически</span></label>)}<div className="research-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Назад</button><button className="primary" onClick={()=>step<3?setStep(step+1):null}>{step<3?"Следующий шаг →":"Бриф заполнен"}</button></div></section><aside className="research-check"><h3>Проверка качества</h3>{checks.map(c=><p className={c.ok?"ok":""} key={c.x}>{c.ok?"✓":"○"} {c.x}</p>)}<button className="primary" disabled={!filled} onClick={download}>Скачать бриф ↓</button></aside></div></main>}
