"use client";
import {useEffect,useState} from "react";
import {evaluateResearchProgress,migrateResearch,RESEARCH_FIELDS} from "../lib/progress-rules.mjs";

const steps=[
 {title:"Проблема и решение",intro:"Исследование начинается с решения, которое предстоит принять, а не с желания «узнать аудиторию».",fields:[["decision","Какое решение нужно принять?","Например: выбрать сегмент для запуска нового тарифа"],["problem","Что сейчас неизвестно?","Каких данных не хватает для решения"]]},
 {title:"Аудитория",intro:"Выберите людей с конкретным опытом и поведением — они смогут рассказать о реальной ситуации.",fields:[["audience","Кого нужно исследовать?","Поведение, ситуация, период времени"],["exclude","Кого не нужно включать?","Границы выборки помогают не смешивать разные задачи"]]},
 {title:"Гипотезы",intro:"До интервью зафиксируйте предположения. Так исследование проверит мышление, а не подтвердит удобную историю.",fields:[["hypotheses","Какие 3 гипотезы проверяем?","1. …\n2. …\n3. …"],["signals","Какие сигналы подтвердят или опровергнут их?","Наблюдаемое поведение, факты, частота"]]},
 {title:"Вопросы и результат",intro:"Спрашивайте о прошлом поведении и конкретных ситуациях, а не о намерениях и фантазиях.",fields:[["questions","Запишите 5 вопросов интервью","Расскажите о последнем случае, когда…"],["output","Как будет выглядеть результат?","Таблица инсайтов, карта пути, рекомендации"]]}
];

export default function ResearchModule(){
 const[step,setStep]=useState(0),[data,setData]=useState(()=>migrateResearch(null)),[editing,setEditing]=useState(true),[storageError,setStorageError]=useState(false);
 useEffect(()=>{try{const saved=migrateResearch(JSON.parse(localStorage.getItem("olymp-research")||"null"));setData(saved);if(saved.completedAt)setEditing(false)}catch{}},[]);
 const persist=next=>{try{localStorage.setItem("olymp-research",JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const update=(k,v)=>{const next={...data,[k]:v};setData(next);persist(next)};
 const rules=evaluateResearchProgress(data);
 const prereqs=rules.details.filter(item=>!item.name.includes("Завершить модуль"));
 const readyToComplete=prereqs.every(item=>item.ok);
 const filled=RESEARCH_FIELDS.filter(k=>String(data[k]||"").trim().length>15).length;
 const progress=Math.round(filled/RESEARCH_FIELDS.length*100);
 const complete=()=>{if(!readyToComplete)return;const next={...data,completedAt:new Date().toISOString()};setData(next);persist(next);setEditing(false);try{window.scrollTo({top:0,behavior:"smooth"})}catch{}};
 const reopen=()=>{setEditing(true);setStep(0)};
 const downloadFile=(name,lines)=>{const blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
 const fieldLines=steps.flatMap(s=>[s.title.toUpperCase(),...s.fields.flatMap(([k,label])=>[label,data[k]||"—",""])]);
 const downloadDraft=()=>downloadFile("research-brief-draft.txt",["МАРКЕТИНГ ОЛИМП — ИССЛЕДОВАТЕЛЬСКИЙ БРИФ",`Дата: ${new Date().toLocaleDateString("ru-RU")}`,"Статус: Черновик","",...fieldLines,"НЕВЫПОЛНЕННЫЕ ТРЕБОВАНИЯ",...(rules.missingRequirements.length?rules.missingRequirements.map(x=>`— ${x}`):["— все требования выполнены"])]);
 const downloadFinal=()=>downloadFile("research-brief.txt",["МАРКЕТИНГ ОЛИМП — ИССЛЕДОВАТЕЛЬСКИЙ БРИФ",`Дата: ${new Date().toLocaleDateString("ru-RU")}`,"Статус: Завершённая учебная работа","",...fieldLines,"ВЫПОЛНЕННЫЕ ПРОВЕРКИ",...rules.completedRequirements.map(x=>`✓ ${x}`),"",`Результат: заполнено ${filled}/${RESEARCH_FIELDS.length} полей, модуль завершён ${data.completedAt?new Date(data.completedAt).toLocaleDateString("ru-RU"):"—"}`,"","Ограничение автоматической оценки: проверяется структура брифа, а не достоверность бизнес-выводов. Перед реальным исследованием покажите бриф наставнику."]);
 if(!editing&&rules.completed)return <main id="main-content" className="research-page"><header><a href="../">← На главную</a><small>МОДУЛЬ 02 · ЗАВЕРШЁН</small><h1>Бриф исследования готов</h1><p>Модуль завершён. Скачайте работу для портфолио или вернитесь и усильте формулировки.</p><div className="research-progress"><i style={{width:"100%"}}/><span>100%</span></div></header>
  <section className="research-complete"><div className="research-complete-score"><strong>{filled}/{RESEARCH_FIELDS.length}</strong><span>полей заполнено</span><b>{data.completedAt?`Завершено ${new Date(data.completedAt).toLocaleDateString("ru-RU")}`:""}</b></div>
   <div className="research-complete-checks"><h2>Проверки качества</h2>{rules.details.map(item=><p className={item.ok?"ok":""} key={item.name}>{item.ok?"✓":"○"} {item.name}{item.detail?` · ${item.detail}`:""}</p>)}<small>Отсутствующие элементы: {rules.missingRequirements.length?rules.missingRequirements.join("; "):"нет"}</small></div>
   <div className="research-final-actions"><button className="primary" onClick={downloadFinal}>Скачать завершённую работу ↓</button><button onClick={reopen}>Вернуться к редактированию</button><a className="research-next-link" href="../strategy/">Перейти к стратегии →</a></div>
  </section></main>;
 return <main id="main-content" className="research-page"><header><a href="../">← На главную</a><small>МОДУЛЬ 02</small><h1>Маркетинговые исследования</h1><p>Соберите исследование, которое помогает принять решение, а не просто производит красивый отчёт.</p><div className="research-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div></header>{storageError&&<div className="storage-warning" role="alert"><b>Не удалось сохранить ответ</b><span>Хранилище браузера недоступно или переполнено. Скопируйте текст в надёжное место, прежде чем продолжать.</span></div>}<div className="research-layout"><aside>{steps.map((x,i)=><button className={step===i?"active":""} onClick={()=>setStep(i)} key={x.title}><span>{i+1}</span>{x.title}</button>)}</aside><section className="research-work"><small>ШАГ {step+1} ИЗ {steps.length}</small><h2>{steps[step].title}</h2><p className="research-intro">{steps[step].intro}</p>{steps[step].fields.map(([key,label,placeholder])=><label key={key}><b>{label}</b><textarea value={data[key]||""} onChange={e=>update(key,e.target.value)} placeholder={placeholder}/><span>Сохраняется автоматически</span></label>)}<div className="research-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Назад</button>{step<3?<button className="primary" onClick={()=>setStep(step+1)}>Следующий шаг →</button>:<button className="primary" disabled={!readyToComplete} onClick={complete}>Завершить модуль →</button>}</div></section><aside className="research-check"><h3>Требования модуля</h3>{prereqs.map(item=><p className={item.ok?"ok":""} key={item.name}>{item.ok?"✓":"○"} {item.name}{item.detail?` · ${item.detail}`:""}</p>)}<button className="primary" disabled={!readyToComplete} onClick={complete}>Завершить модуль →</button><small className="research-complete-hint">{readyToComplete?"Требования выполнены — завершите модуль, чтобы зафиксировать работу.":"Кнопка станет активной после выполнения требований выше."}</small><button className="research-draft" onClick={downloadDraft} disabled={!filled}>Скачать черновик ↓</button></aside></div></main>}
